
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
  namespace: week3-app
spec:
  accessModes:
    - ReadWriteOnce      # OCI block volumes are RWO (single node) by design
  storageClassName: oci-bv
  resources:
    requests:
      storage: 50Gi
